name: Check Prettier & Analyse on SonarQube

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    check-prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Prettier Check
              id: pretier-run
              uses: rutajdash/prettier-cli-action@v1.0.1
              with:
                  config_path: ./.prettierrc
                  file_pattern: ./src/**/*.ts

            - name: Prettier Output
              if: ${{ failure() }}
              shell: bash
              run: |
                  echo "There are files that are not formatted properly. Please run prettier and commit again."

    analyse:
        name: Analyse on SonarQube
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

            - uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

            # If you wish to fail your job when the Quality Gate is red, uncomment the
            # following lines. This would typically be used to fail a deployment.
            - uses: sonarsource/sonarqube-quality-gate-action@master
              timeout-minutes: 5
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
